version: '3.5'

services:
  nginx:
    image: blacklabelops/nginx
    networks:
    - indyscan-net
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - '80:80'
    - '443:443'

networks:
  indyscan-net:
    driver: bridge